vis: Particles.h
	g++ -std=c++0x main.cpp Particles.cpp -o FluidyFun -lGL -lglfw -ldl -lopencv_core -lopencv_highgui

vis_osx: Particles.h
	g++ -std=c++0x -I./glm main.cpp Particles.cpp -o FluidyFun -framework GLUT -framework OpenGL -lopencv_core -lopencv_highgui
